repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files


  - repo: local
    hooks:
      - id: mypy
        name: mypy
        entry: make type-check
        language: system
        types: [python]
        pass_filenames: false

  - repo: local
    hooks:
      - id: format
        name: format
        entry: make format
        language: system
        types: [python]
        pass_filenames: false
      - id: semantic-doc-validation
        name: semantic document validation
        entry: semantic-validate
        language: system
        files: \.(md|markdown)$
        pass_filenames: true
